/** Asset manifest types (spec §83). The manifest is generated by
 *  tools/asset-pipeline and consumed by the client loader + art validation. */

export type AssetType = "image" | "atlas" | "audio" | "font" | "json";

export type PreloadGroup = "core" | "gameplay" | "cosmetic";

export interface AssetEntry {
  id: string;
  type: AssetType;
  /** Path relative to the client's public asset root. */
  path: string;
  /** For atlases: the JSON descriptor path. */
  dataPath?: string;
  width?: number;
  height?: number;
  /** Content-hash version segment for cache busting. */
  version: string;
  preload: PreloadGroup;
  /** Provenance: source master + generation notes (spec §38). */
  meta?: {
    source?: string;
    generated?: string; // ISO date
    purpose?: string;
    license?: string;
  };
}

export interface AssetManifest {
  generatedAt: string;
  pipelineVersion: number;
  entries: AssetEntry[];
}
